import { describe, it, expect } from 'vitest';
import { calculateTable, EXTRAPOLATED_WARNING } from '../performance';
import { traceChart } from '../nomogram';
import type { NomogramMeta } from '../nomogram';
import nomogramMetaRaw from '../../data/nomogram_meta.json';
import { interpolate2D } from '../interpolation';
import fleetRaw from '../../data/fleet.json';
import type { FleetData, PerformanceTable } from '../types';
import fig57 from './fixtures/fig_5_7_takeoff_flaps0_50ft_readings.json';
import fig59 from './fixtures/fig_5_9_takeoff_flaps25_50ft_readings.json';
import fig511 from './fixtures/fig_5_11_takeoff_flaps0_roll_readings.json';
import fig513 from './fixtures/fig_5_13_takeoff_flaps25_roll_readings.json';
import fig515 from './fixtures/fig_5_15_climb_roc_readings.json';
import fig517 from './fixtures/fig_5_17_climb_profile_readings.json';
import fig535 from './fixtures/fig_5_35_landing_flaps40_50ft_readings.json';
import fig537 from './fixtures/fig_5_37_landing_flaps40_roll_readings.json';

const fleet = fleetRaw as unknown as FleetData;
const nomogramMeta = nomogramMetaRaw as unknown as Record<string, NomogramMeta>;
const archer = fleet.N0002;
const table = (id: string) => [...archer.takeoff, ...archer.landing, ...archer.climb.tables].find(t => t.id === id)!;

// Chart readings at in-between conditions, generated by scripts/generate-chart-data.ts
const cases: { name: string; chartId: string; table: PerformanceTable; fixture: { points: { weight: number; altitude: number; oat: number; wind?: number; chartReading: number }[] } }[] = [
  { name: 'Archer II Fig 5-7 (flaps up takeoff, 50 ft)', chartId: 'fig_5_7_takeoff_flaps0_50ft', table: table('takeoff-flaps0-50ft'), fixture: fig57 },
  { name: 'Archer II Fig 5-9 (25° flaps takeoff, 50 ft)', chartId: 'fig_5_9_takeoff_flaps25_50ft', table: table('takeoff-flaps25-50ft'), fixture: fig59 },
  { name: 'Archer II Fig 5-11 (flaps up takeoff ground roll)', chartId: 'fig_5_11_takeoff_flaps0_roll', table: table('takeoff-flaps0-roll'), fixture: fig511 },
  { name: 'Archer II Fig 5-13 (25° flaps takeoff ground roll)', chartId: 'fig_5_13_takeoff_flaps25_roll', table: table('takeoff-flaps25-roll'), fixture: fig513 },
  { name: 'Archer II Fig 5-35 (landing, 50 ft)', chartId: 'fig_5_35_landing_flaps40_50ft', table: table('landing-50ft'), fixture: fig535 },
  { name: 'Archer II Fig 5-37 (landing ground roll)', chartId: 'fig_5_37_landing_flaps40_roll', table: table('landing-roll'), fixture: fig537 },
  { name: 'Archer II Fig 5-15 (rate of climb)', chartId: 'fig_5_15_climb_roc', table: table('climb-roc'), fixture: fig515 },
];

describe.each(cases)('$name: table interpolation vs chart readings', ({ chartId, table, fixture }) => {
  it('has enough chart readings to be meaningful', () => {
    expect(fixture.points.length).toBeGreaterThanOrEqual(500);
  });

  it('is within ±1% of the chart at every reading', () => {
    const misses = fixture.points
      .map(p => {
        const wind = p.wind ?? 0;
        const r = calculateTable({
          weight: p.weight,
          pressureAltitude: p.altitude,
          temperature: p.oat,
          windKnots: Math.abs(wind),
          isHeadwind: wind >= 0,
          surfacePaved: true,
        }, table);
        const pct = r ? (100 * (r.value - p.chartReading)) / p.chartReading : NaN;
        return { ...p, app: r?.value, pct };
      })
      .filter(p => !(Math.abs(p.pct) <= 1));
    expect(misses).toEqual([]);
  });

  it('warns at every condition that runs off the printed chart (fail-closed)', () => {
    // Seeded random conditions across the whole table, including off-chart corners
    let seed = 7;
    const rand = () => (seed = (seed * 16807) % 2147483647) / 2147483647;
    const between = (lo: number, hi: number) => lo + rand() * (hi - lo);
    const silent = [];
    for (let i = 0; i < 2000; i++) {
      const p = {
        weight: between(table.weights[0], table.weights[table.weights.length - 1]),
        altitude: between(table.altitudes[0], table.altitudes[table.altitudes.length - 1]),
        oat: between(table.temperatures[0], table.temperatures[table.temperatures.length - 1]),
        wind: table.windCorrection ? between(-8, 18) : 0,
      };
      if (!traceChart(nomogramMeta[chartId], p).offChart) continue;
      const r = calculateTable({
        weight: p.weight, pressureAltitude: p.altitude, temperature: p.oat,
        windKnots: Math.abs(p.wind), isHeadwind: p.wind >= 0, surfacePaved: true,
      }, table);
      if (!r!.warnings.some(w => w.startsWith(EXTRAPOLATED_WARNING) || w.includes('beyond the POH chart'))) silent.push(p);
    }
    expect(silent).toEqual([]);
  });
});

describe('Archer II Fig 5-17 (time, fuel and distance to climb): table interpolation vs chart readings', () => {
  const profile = archer.climb.profileTable!;

  it('has enough chart readings to be meaningful', () => {
    expect(fig517.points.length).toBeGreaterThanOrEqual(500);
  });

  it.each([
    ['time', profile.timeMinutes],
    ['distance', profile.distanceNm],
    ['fuel', profile.fuelGallons],
  ] as const)('%s is within ±1% (or ±0.1) of the chart at every reading', (name, grid) => {
    // Near sea level the values are about 0.5, where 1% is far finer than the chart can be read:
    // one unit is ~9 px on its scale, so ±0.1 is about 1 px
    const misses = fig517.points
      .map(p => {
        const app = interpolate2D(p.altitude, p.oat, profile.altitudes, profile.temperatures, grid);
        return { ...p, app, diff: app - p[name], pct: (100 * (app - p[name])) / p[name] };
      })
      .filter(p => !(Math.abs(p.pct) <= 1 || Math.abs(p.diff) <= 0.1));
    expect(misses).toEqual([]);
  });
});
